version: '3.8'

services:
  influxdb:
    image: influxdb:2.7.12-alpine
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-storage:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    networks:
      - monitoring-network
    healthcheck:
      test: [ "CMD", "influx", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${USERGRAFANA}
      - GF_SECURITY_ADMIN_PASSWORD=${PASSGRAFANA}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    networks:
      - monitoring-network
    depends_on:
      influxdb:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - monitoring-network
    env_file:
      - .env
    depends_on:
      - influxdb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/docs" ]
      interval: 5s
      timeout: 3s
      retries: 5

  api-monitoreo:
    build:
      context: ./monitoreo
      dockerfile: Dockerfile
    container_name: api-monitoreo
    restart: unless-stopped
    networks:
      - monitoring-network
    env_file:
      - .env
    environment:
      - TZ=America/Santiago
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      influxdb:
        condition: service_healthy
      api:
        condition: service_healthy

volumes:
  grafana-storage:
    driver: local
  influxdb-storage:
    driver: local

networks:
  monitoring-network:
    driver: bridge
