version: '3.8'

services:
  influxdb:
    image: influxdb:2.7.12-alpine
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin_influx
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin_influx
      - DOCKER_INFLUXDB_INIT_ORG=MiOrganizacion
      - DOCKER_INFLUXDB_INIT_BUCKET=estados_programa
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=_ADZL7eFFOaugIzIqoDzXuL5_TkstXUrwmIdvsit9Xi_yHg1EDeUFz2d1QPtbGNkFCVnkHr679MwcdGYcxZVaw==
    networks:
      - monitoring-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/health" ]
      interval: 5s
      timeout: 3s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Claveparalatesis.
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - monitoring-network
    depends_on:
      influxdb:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - monitoring-network
    env_file:
      - .env
    depends_on:
      - influxdb

  api-monitoreo:
    build:
      context: ./monitoreo
      dockerfile: Dockerfile
    container_name: api-monitoreo
    restart: unless-stopped
    networks:
      - monitoring-network
    env_file:
      - .env
    depends_on:
      influxdb:
        condition: service_healthy
      api:
        condition: service_started

volumes:
  grafana-storage:
    driver: local
  influxdb-storage:
    driver: local

networks:
  monitoring-network:
    driver: bridge
